<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Tests.fs" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/SmoothDev.Web/SmoothDev.Web.fsproj" />
  </ItemGroup>
  <Import Project="..\..\..\..\.paket\Paket.Restore.targets" />
</Project>
